### ISSUE TITLE
Camera stream..

### ISSUE THREAD

**Issue by deckchairhq** [jimweirich/argus#3]
I'm using this great library via Artoo (thank you for your hard work on it!)

I wanted to understand how to make use of the video feed, I'd personally like to parse images or a capture feed into open cv but can't find a way to decode a frame into a standalone image or turn a streaming .h264 file into something open cv could use as a capture stream?

Would I be best using some kind of command with ffmpeg separately and just use artoo/argus for navdata and movement?

I've spent a hours upon hours on this so any hint would be grand, and I'm sure useful to others. 

Cheers,

Gareth

**Comment by deadprogram** [comment]
We're working on a Artoo driver that hooks the video frames to FFMPEG for parsing to PNG, and another Artoo driver to hook up images to Ruby CV... more shall be revealed in the near future. Strictly speaking, this is not a direct concern of Argus itself, however.

**Comment by jimweirich** [comment]
What Ron said ... Since this is more of an Artoo issue, I'm closing this.
